#!/home/wayne/.rvm/rubies/ruby-2.0.0-p247/bin/ruby
require 'rubygems'
require 'mechanize'
require 'colorize'

#swedbank credentials - path to file
path_to_file = "#{ENV['HOME']}/" + "swedbank_credentials"

# try to read the config file. fail with message to user 
begin
 config = File.open(path_to_file).read
rescue
 puts "Error! Could not find #{path_to_file}. Please make sure it exists.".red
end

# read the login credentials 
id  = config.split(/\n/)[0]  # personnummer
pwd = config.split(/\n/)[1]  # lösenord

# bank uris
page_landing     = 'https://mobilbank.swedbank.se/banking/swedbank/login.html'
page_auth_method = '/banking/swedbank/loginNext.html'
page_password    = '/banking/swedbank/login.html'
page_account_info= '/banking/swedbank/accounts.html'

# mechanizer 
agent = Mechanize.new

# start with the login page
agent.get(page_landing) do |page|
  
  #authorize user
  print "Initializing authorization......".black
    #step one : enter registration number and select method of authorization
    step_one = page.form_with(:action => page_auth_method) do |form|
      form.xyz = id
      form.field_with(:name => 'auth-method').options[0].select
    end.click_button
  
    #step two : enter the password
    step_two = step_one.form_with(:action => page_password) do |form|
      form.zyx = pwd
    end.click_button
  puts "success!".black
  
 #fetch account information
  print "Fetching account information....".black
    overview = step_two.link_with(:href => page_account_info).click
    #placeholders for printable information
    accounts = Hash.new
    overview.search('.list-content dd').each do |account|
      accounts[account.search('.name').text.strip.blue] = account.search('.amount').text.strip.yellow
    end
  puts "success!".black

  # Print account info -
  account_name_length    = 35
  account_balance_length = 30
  puts "Account information".green
  accounts.each {|account_name, account_balance|
  	dots   = '.'.blue * (account_name_length  - account_name.length) 
  	dots_n = '.'.blue * (account_balance_length - account_balance.delete(' ').length)
  	puts "#{account_name}#{dots}#{dots_n}#{account_balance.delete(' ')}" + " kr".yellow
  }
  
end